### PR TITLE
Point to code

### PR DESCRIPTION
**Pull request by ebuchman**

### CODE REVIEW

**Comment by gubatron** [comment]
can anyone confirm [that is the actual code](https://github.com/openblockchain/obc-peer)?

Lot of news outlets today talking about the code release, only to come here and still see a README file.

**Comment by christo4ferris** [comment]
@gubatron yes, that is IBM's _proposed_ contribution - it is up to the Hyperledger Project and the TSC to actually agree that that would be the starting base from which we develop. I believe that there will be formal proposals discussed during this week's TSC.

**Comment by ebuchman** [comment]
I would recommend all parties adopt [Tendermint](https://github.com/tendermint/tendermint) as the core consensus engine as its Byzantine Fault Tolerance algorithm is highly efficient and provides the strongest guarantees. It is also now incredibly easy to write applications, in any language, on top. Indeed, it would be possible to integrate some of IBMs work in on top.

**Comment by gubatron** [comment]
sweet!
Thanks @christo4ferris for the clarification.

**Comment by ameadors** [comment]
Thanks Christopher

Where is the TSC being held ?

Can you please share the proposed ideas with remote community

thanks
- Andrew

On Feb 16, 2016, at 4:54 PM, Christopher Ferris <notifications@github.com<mailto:notifications@github.com>> wrote:

@gubatronhttps://github.com/gubatron yes, that is IBM's proposed contribution - it is up to the Hyperledger Project and the TSC to actually agree that that would be the starting base from which we develop. I believe that there will be formal proposals discussed during this week's TSC.

**Comment by christo4ferris** [comment]
The discussion happens on the email list and the info about the weekly TSC calls is posted on the website: https://www.hyperledger.org/community

**Comment by dazraf** [comment]
+1 for TenderMint PBFT implementation

**Comment by ScroogeMcDuckButWithBitcoin** [comment]
Wow - am I to understand that this is an append-only database? This is going to be so useful, I can't believe no one thought of doing something like that sooner.

**Comment by zamrokk** [comment]
@ScroogeMcDuckButWithBitcoin I think you don't get the point. Read more about Blockchain technology first and you will understand why

**Comment by ScroogeMcDuckButWithBitcoin** [comment]
I've looked into it a little. It seems like you put your transactions into folders, checksum them, and then broadcast the folders. So it sounds a lot like PGP encrypted email, but sent to everyone on the network. Which I'm guessing would be really useful for bankers.

**Comment by quiquee** [comment]
That is the best explanation of blockchain technology that I have ever
heard. Thanks Benjamin, you can be sure I am using it from now on

**Comment by jonathanferrier** [comment]
Dido

**Comment by mkdolan** [comment]
Hi all, just FYI we updated the README yesterday with pointers to community proposed core code contributions. The TSC will be evaluating various proposals and combinations and setup core projects to work on the code. 

[https://github.com/hyperledger/hyperledger](https://github.com/hyperledger/hyperledger)

**Comment by gubatron** [comment]
@mkdolan much thanks! it's so much better now.
thank you

**Pull request closed without merging**
