### PR TITLE
initial outline

### PR DESCRIPTION
**Pull request by christo4ferris**
initial outline

### CODE REVIEW

**Comment by christo4ferris** [comment]
I offer this as an initial draft outline for the Hyperledger project's whitepaper. As we have yet to devise a formal process for it's development, I would also propose that we use the comments to build consensus on agreement to merge changes, starting with this. I would also propose that the team that is developing the use cases and requirements take on the formal role of managing this along with those use cases and requirements.

**Comment by Horizon88** [comment]
following this and whitepaper.md - good proposal! @christo4ferris 

I have a use case to propose. Who is the team that is developing use cases?

**Comment by christo4ferris** [comment]
@horizon88 Patrick Holmes sent a note to the hyperledger-tsc looking for volunteers to contribute to the use case and requirements working group.

**Comment by pjholmes** [comment]
patrick.holmes@intel.com. @Horizon88, I look forward to your input.

**Comment by vishalya** [comment]
@christo4ferris, so based on your comments here, is Patrik Homles the point contact to develop this whitepaper work going forward?

**Pull request merged**
