### PR TITLE
I've fixed up your hyperledger with a working blockchain implementation

### PR DESCRIPTION
**Pull request by obscuren**
:trollface:

### CODE REVIEW

**Comment by frozeman** [comment]
+1

**Comment by akinmail** [comment]
Finally something interesting

**Comment by frozeman** [comment]
I wonder how this repository could get 869 stars without one line of code. Are this stars of anticipation :D

**Comment by murraci** [comment]
Wonderful suggestion.

**Comment by jeremyeder** [comment]
ship it

**Comment by ghost** [comment]
ACK

**Comment by rfikki** [comment]
+2

**Comment by AndrewKeysConsenSys** [comment]
Best April Fool's of the year.

**Comment by kumavis** [comment]
LGTM

**Comment by texture** [comment]
Problem solved.

**Pull request closed without merging**
