### PR TITLE
use a pojo as a ledger

### LINKED ISSUE #1: where's the code?

### PR DESCRIPTION
**Pull request by buhrmi**
fixes #1

### CODE REVIEW

**Comment by asanz** [comment]
👍

**Comment by ebuchman** [comment]
Ledger should be capitalized. Please read the contribution guidelines before submitting PRs. Otherwise, great work!

**Comment by joshuajeeson** [comment]
😎👍

**Comment by EtherTyper** [comment]
:+1: POJO vs IBM's solution? POJO any day. :laughing:

**Pull request closed without merging**
